services:
  api:
    container_name: 'ai-service'
    build:
      context: ./
      dockerfile: Dockerfile
    image: ai-service
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=http://host.docker.internal
      - POSTGRES_HOST=pgvector
    ports:
      - "9000:9000"
    depends_on:
      pgvector:
        condition: service_healthy
    command: ["node","./index.js"]
 
  pgvector:
    container_name: 'pgvector'
    image: ankane/pgvector
    restart: always
    volumes:
      - ./pgvector/scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data:rw
    ports: ["${POSTGRES_PORT}:${POSTGRES_PORT}"]
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
 
  adminer:
    container_name: 'postgres_adminer'
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db-data: {}